baseURL = "https://wonderful-ritchie-8e5030.netlify.app/"
languageCode = "en-us"
title = "JAMSite"
theme = "tale"
copyright = "Copyright 2019 Stackacademy.tv"
disableKinds = ["section"]

[outputs]
  home = ["HTML", "JSON"]
