baseURL = "https://heinzb-2021.github.io/Test1/"
languageCode = "en-us"
title = "JAMSite"
theme = "tale"
copyright = "Copyright 2019 Stackacademy.tv"
disableKinds = ["section"]

[outputs]
  home = ["HTML", "JSON"]
